package cms.business;

import java.awt.image.BufferedImage;

/**
 * Interface describing a page, that can be generated by the CMS.
 *
 * @author Kasper
 */
public interface DynamicPage {

	/**
	 * The name of the attribute to use as id.
	 */
	String ID_ATTRIB = "id";

	/**
	 * Test whether the id of this page is valid.
	 *
	 * @return true if the id is valid, false otherwise
	 */
	boolean hasValidID();

	/**
	 * Get the id of this page.
	 *
	 * @return the id of this page
	 */
	int getID();

	/**
	 * Set the id of this page. This operation will be ignored if the id is already set. The purpose of this method is
	 * to allow the persistence layer to assign an id to a page created in the domain layer.
	 *
	 * @param id the id of the page
	 */
	void setID(int id);

	/**
	 * Get the content for the template element with the specified id. The content will be wrapped in a {@code <div>}
	 * element, and should thus be unwrapped by calling {@link XMLElement#getChildren()}.
	 *
	 * @param id the id of the template element
	 * @return the content for the template element with the specified id
	 */
	XMLElement getContentForID(String id);

	/**
	 * Insert the specified html markup at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the markup into
	 * @param html   the markup to insert
	 */
	void insertHTML(DocumentMarker marker, String html);

	/**
	 * Insert the specified text at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the text into
	 * @param text   the text to insert
	 */
	void insertText(DocumentMarker marker, String text);

	/**
	 * Insert the specified image at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the image into
	 * @param image  the image to insert
	 */
	void insertImage(DocumentMarker marker, BufferedImage image);

	/**
	 * Remove the element at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the element from
	 */
	void removeElement(DocumentMarker marker);

	/**
	 * Get the text from this page at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to get the text from
	 * @return the text at the specified information
	 */
	String getTextSelection(DocumentMarker marker);

	/**
	 * Get the link from this page at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to get the link from
	 * @return the link at the specified information
	 */
	Link getLinkSelection(DocumentMarker marker);

	/**
	 * Replace the text at the location specified by the {@link DocumentMarker} with the specified link.
	 *
	 * @param marker the location of the text to replace
	 * @param link   the link to insert
	 */
	void setTextLink(DocumentMarker marker, Link link);

	/**
	 * Remove the link at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the link from
	 */
	void removeLink(DocumentMarker marker);
}
