package cms.business;

import java.awt.image.BufferedImage;

/**
 * Interface describing a page, that can be generated by the CMS.
 *
 * @author Kasper
 */
public interface DynamicPage {

	/**
	 * The name of the attribute to use as id.
	 */
	String ID_ATTRIB = "id";

	/**
	 * Get the content for the template element with the specified id.
	 *
	 * @param id the id of the template element
	 * @return the content for the template element with the specified id
	 */
	XMLElement getContentForID(String id);

	/**
	 * Insert the specified html markup at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the markup into
	 * @param html   the markup to insert
	 */
	void insertHTML(DocumentMarker marker, String html);

	/**
	 * Remove the html markup at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the markup from
	 */
	void removeHTML(DocumentMarker marker);

	/**
	 * Insert the specified text at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the text into
	 * @param text   the text to insert
	 */
	void insertText(DocumentMarker marker, String text);

	/**
	 * Remove the text at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the text from
	 */
	void removeText(DocumentMarker marker);

	/**
	 * Insert the specified image at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to insert the image into
	 * @param image  the image to insert
	 */
	void insertImage(DocumentMarker marker, BufferedImage image);

	/**
	 * Remove the image at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the image from
	 */
	void removeImage(DocumentMarker marker);

	/**
	 * Get the text from this page at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to get the text from
	 * @return the text at the specified information
	 */
	String getTextSelection(DocumentMarker marker);

	/**
	 * Get the link from this page at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to get the link from
	 * @return the link at the specified information
	 */
	Link getLinkSelection(DocumentMarker marker);

	/**
	 * Replace the text at the location specified by the {@link DocumentMarker} with the specified link.
	 *
	 * @param marker the location of the text to replace
	 * @param link   the link to insert
	 */
	void setTextLink(DocumentMarker marker, Link link);

	/**
	 * Remove the link at the location specified by the {@link DocumentMarker}.
	 *
	 * @param marker the location to remove the link from
	 */
	void removeLink(DocumentMarker marker);
}
